# https://taskfile.dev

version: '3'

vars:
  BIN_NAME: azactl

tasks:
  test:
    desc: "Run the tests"
    cmds:
      - go test ./cmd -coverprofile=covetage.out

  build.win:
    desc: "Build for windows platform"
    cmds:
      - go build -o {{ .BIN_NAME }}.exe -a -ldflags "-s -w"
    env:
      GOOS: windows
      GOARCH: amd64

  build:
    desc: "Build for linux platform"
    cmds:
      - go build -o {{ .BIN_NAME }} -a -ldflags "-s -w"
    env:
      GOOS: linux
      GOARCH: amd64

  build.mac:
    desc: "Build for macos platform"
    cmds:
      - go build -o {{ .BIN_NAME }} -a -ldflags "-s -w"
    env:
      GOOS: darwin
      GOARCH: amd64
